In [1]:
import numpy as np

a = np.random.randn(5)
print(a)



[-1.97660667  0.68846277 -0.95031482 -0.08747191 -0.27027288]


In [2]:
print(a.shape)

(5,)


In [3]:
print(a.T)

[-1.97660667  0.68846277 -0.95031482 -0.08747191 -0.27027288]


In [4]:
print(np.dot(a,a.T))

5.364751921412212


In [5]:
a=np.random.randn(5,1)
print(a)

[[-0.99383588]
 [ 0.21938744]
 [ 1.2352735 ]
 [-0.30623981]
 [ 1.29085981]]


In [6]:
print(a.T)

[[-0.99383588  0.21938744  1.2352735  -0.30623981  1.29085981]]


In [8]:
print(np.dot(a,a.T))

[[ 0.98770975 -0.21803511 -1.22765912  0.30435211 -1.28290279]
 [-0.21803511  0.04813085  0.27100349 -0.06718517  0.28319843]
 [-1.22765912  0.27100349  1.52590062 -0.37828992  1.59456491]
 [ 0.30435211 -0.06718517 -0.37828992  0.09378282 -0.39531266]
 [-1.28290279  0.28319843  1.59456491 -0.39531266  1.66631905]]


In [13]:
a = np.random.randint(5, size=(3, 4))
b = np.random.randint(5, size=(4, 1))
c = np.random.randint(5, size=(3, 4))
print(a)
print(b)
for i in range(3):
    for j in range(4):
        c[i][j] = a[i][j] + b[j]
print(c)   

[[3 2 3 3]
 [2 4 3 4]
 [0 4 1 3]]
[[3]
 [1]
 [2]
 [2]]
[[6 3 5 5]
 [5 5 5 6]
 [3 5 3 5]]


In [17]:
c=a+b.T

print(c)

[[6 3 5 5]
 [5 5 5 6]
 [3 5 3 5]]
